version: '3.8'
services:
  api:
    build: ./BE/
    container_name: api
    restart: always
    networks:
      - pg-network
    depends_on:
      - postgres
  postgres:
    image: postgres:alpine
    container_name: ${PG_HOST}
    environment:
      POSTGRES_DB: ${PG_DATABASE_NAME}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_USER: ${PG_USER}
    ports:
      - ${PG_PORT}:5432
    restart: on-failure:3
    networks:
      - pg-network

  pgweb_adminer:
    image: adminer
    container_name: ${ADMINER_HOST}
    environment:
      DATABASE_URL: postgres://${PG_USER}:${PG_PASSWORD}@${PG_HOST}:${PG_PORT}/${PG_DATABASE_NAME}?sslmode=disable
    ports:
      - ${ADMINER_PORT}:8080
    restart: on-failure:3
    depends_on:
      - postgres
    networks:
      - pg-network

volumes:
  pg-data:

networks:
  pg-network:
    driver: bridgea





